# Generated by Django 5.2 on 2025-04-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='yanit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
